TOP_SRCDIR = ../..
KERN_SRCDIR= ..
include $(TOP_SRCDIR)/Makefile.mk

OUTDIR=$(BUILDDIR)/tests/vector
TARGETNAME=vector

OBJS = Vector.o
_OBJS = $(addprefix $(OUTDIR)/,$(OBJS))

include $(TOP_SRCDIR)/tests/Makefile.tests.mk



