TOP_SRCDIR = ../..
KERN_SRCDIR= ..

OBJS = console.o \
	devfull.o \
	devhda.o \
	devhdainfo.o \
	devnull.o \
	devperfctr.o \
	devrandom.o \
	devsound.o \
	devzero.o \
	ide.o \
	ioapic.o \
	kbd.o \
	lapic.o \
	mp.o \
	picirq.o \
	sound.o \
	timer.o \
	uart.o \

include $(KERN_SRCDIR)/Makefile.common
