TOP_SRCDIR = ../..
KERN_SRCDIR= ..
include $(TOP_SRCDIR)/Makefile.mk

OUTDIR=$(BUILDDIR)/tests/priority_queue
TARGETNAME=priority_queue

OBJS = PriorityQueue.o
_OBJS = $(addprefix $(OUTDIR)/,$(OBJS))

include $(TOP_SRCDIR)/tests/Makefile.tests.mk



